### ISSUE TITLE
UI design

### ISSUE THREAD

**Issue by G4me8woy** [josh-boat365/aqms#2]
design the user interface for the system

**Comment by josh-boat365** [comment]
I have uploaded files for the UI Design - Landing Page(Desktop & Mobile View), Sign in & Sign up Page(Desktop View)
![Landing Page1](https://user-images.githubusercontent.com/60707857/137548435-1c9c6667-e9c8-45de-ac4b-bdcd10e00d72.png)
![Landing Page2](https://user-images.githubusercontent.com/60707857/137548444-8ea18ba7-bcb4-49c3-8b46-fe52d60e9573.png)
![Landing-Page-Mobile-View](https://user-images.githubusercontent.com/60707857/137548446-7aa9758a-43ee-410c-9ee9-9c178fcaf081.png)
![Login Page](https://user-images.githubusercontent.com/60707857/137548448-159a9be3-53ff-4718-b4c6-1feaef97a1bd.png)
![Sign Up](https://user-images.githubusercontent.com/60707857/137548449-c0cd06a7-f1ac-4380-91aa-5adb4f9007fc.png)
