### ISSUE TITLE
building the context menu for the survey tiles

### ISSUE THREAD

**Issue by Fuad2Dev** [josh-boat365/aqms#33]
> drafted
- delete ✔
- move to deployed ✔

> deployed
- move to archive ✔

> archive
- view responses ✔

**Comment by josh-boat365** [comment]
Can you kindly give in-depth explanation i don't get it

**Comment by Fuad2Dev** [comment]
a context menu for when you right click on a survey tile

**Comment by Fuad2Dev** [comment]
I'm done with the UI, as in displaying the respective menus on right click

**Comment by josh-boat365** [comment]
Nice works, have reviewed it but for viewing responses on archived survey doesn't work
