### ISSUE TITLE
Landing Page Design

### ISSUE THREAD

**Issue by josh-boat365** [josh-boat365/aqms#7]
Create a welcome page to initiate alumni's and give alumni's a fair idea of what to do on the system
@ManuelDCoder you will handle responsiveness

**Comment by josh-boat365** [comment]
## Mobile View - @ManuelDCoder 

![Landing-Page-Mobile-View](https://user-images.githubusercontent.com/60707857/137469323-726b4fa6-ee92-4ba3-a13e-9678359441e6.png)

**Comment by ManuelDCoder** [comment]
Sure.
Will work on it
